<a href="https://colab.research.google.com/github/Yuliana-Lestari/data-science-2026/blob/main/Pertemuan3_YulianaLestari_250401020199.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UTS Data Science - Universitas Siber Asia
* **Nama Lengkap:** Yuliana Lestari
* **NIM:** 250401020199
* **Kelas:** IF403

In [1]:
from google.colab import files

uploaded = files.upload()

Saving housing_dirty.csv to housing_dirty.csv

In [2]:
import pandas as pd

df = pd.read_csv('housing_dirty.csv')

df.head()

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    NaN          1995   Bagus
2   3    249.7       895.0  Depok    NaN          1983    baik
3   4     49.7       178.0    YGY    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  Sedang

In [3]:
import pandas as pd

df = pd.read_csv('housing_dirty.csv')

df.head()

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    NaN          1995   Bagus
2   3    249.7       895.0  Depok    NaN          1983    baik
3   4     49.7       178.0    YGY    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  Sedang

In [4]:
import pandas as pd
import numpy as np
import missingno as msno
from scipy.stats.mstats import winsorize

In [5]:
df = pd.read_csv('housing_dirty.csv')

print(df.head())

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    NaN          1995   Bagus
2   3    249.7       895.0  Depok    NaN          1983    baik
3   4     49.7       178.0    YGY    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  Sedang

In [6]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            130 non-null    int64
 1   luas_m2       112 non-null    float64
 2   harga_juta    113 non-null    float64
 3   kota          130 non-null    object
 4   kamar         120 non-null    float64
 5   tahun_bangun  130 non-null    int64
 6   kondisi       130 non-null    object
dtypes: float64(3), int64(2), object(2)
memory usage: 7.2+ KB
None
               id      luas_m2    harga_juta       kamar  tahun_bangun
count  130.000000   112.000000  1.130000e+02  120.000000    130.000000
mean    65.500000   267.627679  8.856325e+05    3.433333   2062.638462
std     37.671829   885.664181  9.407144e+06    1.776283    701.684043
min      1.000000   -50.000000 -5.000000e+02    1.000000   1890.000000
25%     33.250000    87.050000  3.450000e+02    2.000000   1991.250000
50%     65.500000   193.800000  6.550000e+02    4.000000   2002.000000
75%     97.750000   280.675000  9.550000e+02    5.000000   2011.750000
max    130.000000  9500.000000  1.000000e+08    6.000000   9999.000000
id               0
luas_m2         18
harga_juta      17
kota             0
kamar           10
tahun_bangun     0
kondisi          0
dtype: int64

In [7]:
print("Sebelum:", df.shape)

df.drop_duplicates(inplace=True)

print("Sesudah:", df.shape)

Sebelum: (130, 7)
Sesudah: (130, 7)

In [8]:
df['kota'] = df['kota'].str.strip().str.title()
df['kondisi'] = df['kondisi'].str.strip().str.lower()

print(df[['kota','kondisi']].head())

    kota kondisi
0  Jogja    baik
1  Medan   bagus
2  Depok    baik
3    Ygy    baik
4  Medan  sedang

In [9]:
df['luas_m2'] = df['luas_m2'].fillna(df['luas_m2'].median())

df['harga_juta'] = df['harga_juta'].fillna(df['harga_juta'].median())

df['kamar'] = df['kamar'].fillna(df['kamar'].mode()[0])

print(df.isnull().sum())

id              0
luas_m2         0
harga_juta      0
kota            0
kamar           0
tahun_bangun    0
kondisi         0
dtype: int64

In [10]:
for col in ['harga_juta', 'luas_m2', 'tahun_bangun']:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower, upper)

print("Outlier berhasil ditangani")

Outlier berhasil ditangani

In [11]:
print(df.isnull().sum().sum())
print(df.duplicated().sum())

0
0

In [12]:
df.to_csv('housing_clean.csv', index=False)

print("Dataset berhasil disimpan")

Dataset berhasil disimpan

In [13]:
import requests
from pandas import json_normalize

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

data = response.json()

df_api = json_normalize(data)

print(df_api[['id','name','email']])

   id                      name                      email
0   1             Leanne Graham          Sincere@april.biz
1   2              Ervin Howell          Shanna@melissa.tv
2   3          Clementine Bauch         Nathan@yesenia.net
3   4          Patricia Lebsack  Julianne.OConner@kory.org
4   5          Chelsey Dietrich   Lucio_Hettinger@annie.ca
5   6      Mrs. Dennis Schulist    Karley_Dach@jasper.info
6   7           Kurtis Weissnat     Telly.Hoeger@billy.biz
7   8  Nicholas Runolfsdottir V       Sherwood@rosamond.me
8   9           Glenna Reichert    Chaim_McDermott@dana.io
9  10        Clementina DuBuque     Rey.Padberg@karina.biz

### Kesimpulan Praktikum (Pertemuan 3)

  Pada pertemuan ini, saya mempelajari pentingnya kualitas data dan tahapan tahapan kritis pembersihan data (data cleaning) untuk menghindari prinsip "Garbage In, Garbage Out". Materi meliputi deteksi dan penanganan data hilang (missing values), penanganan data duplikat, penyaringan nilai ekstrem (outlier), normalisasi inkonsistensi string, serta teknik ekstraksi data semi-terstruktur dari file JSON lokal maupun REST API publik menggunakan library requests.

  1. Tahap penyiapan dan pembersihan data (data preparation & cleaning) menyita porsi waktu terbesar dalam kerja nyata seorang Data Scientist (sekitar 37.75% berdasarkan industri).
  2. Penanganan missing values harus disesuaikan dengan tipenya (MCAR, MAR, MNAR) menggunakan metode drop atau imputasi (statistik/KNN Imputer), sedangkan pencarian outlier dapat diselesaikan secara objektif lewat metode IQR Fence atau Z-Score, lalu dikelola menggunakan teknik capping (Winsorization).
  3. Berhasil menyusun kodingan pipeline pembersihan data secara otomatis dari tahap load, penghapusan duplikat, normalisasi huruf kapital teks, pengisian data kosong, hingga pembatasan nilai ekstrem lewat fungsi.

  Ketika menangani outlier menggunakan metode pemotongan ekstrem atau pengisian nilai kosong (imputasi), tindakan ini secara tidak langsung mengubah distribusi asli dari data mentah. Bagaimana kita mengukur batas aman agar modifikasi data selama proses cleaning ini tidak malah membuang informasi berharga atau membiaskan hasil prediksi model machine learning nantinya?